Fix aborting when clone fails

diff --git a/bin/ryogoku b/bin/ryogoku
--- a/bin/ryogoku
+++ b/bin/ryogoku
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION="0.4.3"
+VERSION="0.4.4"
 CONFIG=ryogoku.conf
 ENV=
 REF=
@@ -249,7 +249,10 @@ deploy() {
 
   local repository=$(pwd)
   (cd $TMP; git rev-parse 2> /dev/null)
-  test $? -ne 0 && (cd $TMP; git clone $repository . || abort failed to clone)
+  if test $? -ne 0; then
+    (cd $TMP; git clone $repository .) || abort failed to clone
+  fi
+#  test $? -ne 0 && (cd $TMP; git clone $repository .) || abort failed to clone
 
   # check remote url
   local remote_url=$(cd $TMP > /dev/null 2>&1 && git remote -v | grep -m 1 ^origin | cut -f 2 | cut -d ' ' -f 1)
@@ -257,7 +260,7 @@ deploy() {
     log working directory path changed. clone again from the new path.
     rm -rf $TMP
     mkdir -p $TMP
-    (cd $TMP; git clone $repository . || abort failed to clone)
+    (cd $TMP; git clone $repository .) || abort failed to clone
   fi
 
   # fetch source
